<!DOCTYPE html>
<html lang="en-us">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title> 魔方铺源(管理工具) </title>
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/bootstrap.min.css">	
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/font-awesome.min.css">

		<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-production.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-skins.css">	
		
		<!-- SmartAdmin RTL Support is under construction
			<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->
		
		<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/demo.css">

		<!-- page related CSS -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/lockscreen.css">

		<!-- FAVICONS -->
		<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">

		<!-- GOOGLE FONT -->
		<link rel="stylesheet" href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">
		<style>
        .lockscreen .logo + div > img + div {
            float: left;
            width: 320px;
        }
      
 
 

        </style>
    <script type="text/javascript">
    
 	/**
	if(userAgent.indexOf("firefox")<1){

		alert("请下载火狐浏览器登陆后台！");
		window.location.href="http://download.firefox.com.cn/releases/stub/official/zh-CN/Firefox-latest.exe";
		return false;
		
	}
	*/
	
      </script>

	</head>
	<body>
 
 

		<div id="main" role="main">

			<!-- MAIN CONTENT -->

			<form id="form1" class="lockscreen animated flipInY smart-form" action="/admin/login/dologin">
				<div class="logo">
					 <img src="/resources/img/logo.png" alt="" style="width:167px;height:27px;" /> 
				</div>
				<div>
					<img border="1px" style="border:1px solid #ccc;" src="/resources/img/avatars/male.png" alt="" width="120" height="120" />
					<div style="margin-left:0px;">
						            <h1 style="margin-left:10px;"><i class="fa fa-user fa-4x text-muted air air-top-right hidden-mobile" style="z-index:0;"></i>管理登录</h1>
								    
								    <section  class="col col-10" style="margin-top:15px;">
										<label class="input" style="margin:0;"> <i class="icon-append fa fa-user"></i>
											<input type="text" name="username" id="username" placeholder="手机号码">
											<b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> 请输入手机号码</b>
										</label>
										<i></i>	
										
									</section>
									<div class="btn-group col col-2" style="margin-left:0px;padding-left:0;margin-top:16px;">
										<a class="btn btn-primary btn-sm" id="btnSendCode" style="font-size: 11px;padding:2px;" href="javascript:void(0);">发送验证码</a>
									</div> 
									  <section class="col col-10">
											<label class="input" style="margin:0;"> <i class="icon-append fa fa-lock"></i>
												<input type="text" id="password" name="password" placeholder="短信验证码">
												<b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> 请输入短信验证码</b> </label>
										     <i></i>  
										    
									   </section>
									   <div class="btn-group col col-2" style="margin-left:0px;padding-left:0;margin-top:4px;">
							                    <button id="btnSubmit" type="button" class="btn btn-primary" style="padding:3px;">
							                        <i class="fa fa-key"></i>&nbsp;登录
							                    </button>
						                </div>
								   
									
					</div>

				</div>
				<p class="font-xs margin-top-5">
					copyright © www.mofangpu.com 2017. 用火狐浏览器更好的体验

				</p>
			</form>

		</div>

		<!--================================================== -->	

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)
		<script data-pace-options='{ "restartOnRequestAfter": true }' src="/js/plugin/pace/pace.min.js"></script>-->

	    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
		<script> if (!window.jQuery) { document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');} </script>

		<script> if (!window.jQuery.ui) { document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');} </script>
		<script src="/resources/js/jquery.alerts.js" type="text/javascript"></script>
		<link href="/resources/css/jquery.alerts.css" rel="stylesheet" type="text/css" media="screen" />
		<script src="/resources/js/jquery.form.js"></script>
		<script src="/resources/js/jquery.validate.js"></script>
		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events 		
		<script src="/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->		
		<script src="/resources/js/bootstrap/bootstrap.min.js"></script>

		<!-- CUSTOM NOTIFICATION -->
		<script src="/resources/js/notification/SmartNotification.min.js"></script>

		<!-- JARVIS WIDGETS -->
		<script src="/resources/js/smartwidgets/jarvis.widget.min.js"></script>
		
		<!-- EASY PIE CHARTS -->
		<script src="/resources/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
		
		<!-- SPARKLINES -->
		<script src="/resources/js/plugin/sparkline/jquery.sparkline.min.js"></script>
		
		<!-- JQUERY VALIDATE -->
		<script src="/resources/js/plugin/jquery-validate/jquery.validate.min.js"></script>
		
		<!-- JQUERY MASKED INPUT -->
		<script src="/resources/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
		
		<!-- JQUERY SELECT2 INPUT -->
		<script src="/resources/js/plugin/select2/select2.min.js"></script>

		<!-- JQUERY UI + Bootstrap Slider -->
		<script src="/resources/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
		
		<!-- browser msie issue fix -->
		<script src="/resources/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>
		
		<!-- FastClick: For mobile devices -->
		<script src="/resources/js/plugin/fastclick/fastclick.js"></script>
		
		<!--[if IE 7]>
			
			<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
			
		<![endif]-->
		
		<!-- MAIN APP JS FILE -->
		<script src="/resources/js/app.js"></script>
		<script src="/resources/js/demo.js"></script>
		<script type="text/javascript">
		
			$(function(){

				function isNull(str) {
				    if (str == "") return true;
				    var regu = "^[ ]+$";
				    var re = new RegExp(regu);
				    return re.test(str);
				}

				var isPhone = 1;
				//验证手机号码
				function checkPhone(){
					var phone = $('#username').val();
					isPhone = 1;
					if(isNull(phone)) {
						$('#username').focus();
// 						alert('请输入手机号码');
						nbox('请输入手机号码',0);
						
						isPhone = 0;
						return;
					}
					
					if(phone.length!=11){
						$('#username').focus();
						nbox('手机号码格式错误',0);
						isPhone = 0;
						return;
					}

					

					$.ajax({  
					      type:"POST",  
					      async:false,  
					      url:"/index.php?m=admin&c=login&a=sendSms",  
					      data:{ 'phone':phone },  
					      dataType:'json',
					      success:function(res){  
						      
					          if(res.status==1){
								  nbox("发送成功",1);
						      }else{
                                  nbox( res.msg , 0 );
							  }
					      } 
					  });  
				 	
				
				}
				//倒计时
				function resetCode(){
					 
					$('#btnSendCode').html('60秒').addClass("disabled");
					var second = 60;
					var timer = null;
					timer = setInterval(function(){
						second -= 1;
						if(second >0 ){
							$('#btnSendCode').html(second+"秒").addClass("disabled");
						}else{
							$('#btnSendCode').html('获取验证码').removeClass("disabled");
						}
					},1000);
				}

				$("#btnSendCode").click(function(){
					checkPhone(); //验证手机号码
					if(isPhone && $("#btnSendCode").val()!="获取验证码"){
						resetCode(); //倒计时
					}else{
						$('#username').focus();
					}
					
				});

				$("#btnSubmit").click(function(){
					var phone = $("#username").val();
					var password = $("#password").val();
					
					if(isNull(phone)) {
						$('#username').focus();
						nbox('请输入手机号码',0);
						isPhone = 0;
						return;
					}
					
					if(phone.length!=11){
						$('#username').focus();
						nbox('手机号码格式错误',0);
						return;
					}

					if(isNull(password)) {
						$('#password').focus();
						nbox('请输入短信验证码',0);
						return;
					}

					$.ajax({  
					      type:"POST",  
					      async:false,  
					      url:"/index.php?m=admin&c=login&a=checkLogin",  
					      data:{ 'phone':phone,'password':password },  
					      dataType:'json',
					      success:function(res){  
						      
					          if(res.status==1){
						          nbox('验证成功',1);
						          setTimeout(function(){
						        	  window.location.href='/index.php?m=admin&c=index&a=index';
							          },2000);
						      }else{
                              	  nbox( res.msg,0 );
							  }
					      } 
					  });  
				 	
					
					
				});

				 
			});
		</script>
        
   
	</body>

</html>