<!DOCTYPE html>
<html lang="en-us">
	<head>
		<meta charset="utf-8">
		<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

		<title> 魔方铺源(管理工具) </title>
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/font-awesome.min.css">

		<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-production.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-skins.css">

		<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

		<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/demo.css">

		<!-- FAVICONS -->
		<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">

		<!-- GOOGLE FONT -->
		<link rel="stylesheet" href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">

	</head>
	<body class="">
<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- RIBBON -->
	<div id="ribbon">

		<span class="ribbon-button-alignment"> <span id="refresh"
			class="btn btn-ribbon" data-title="refresh" rel="tooltip"
			data-placement="bottom" data-original-title="<i 
			class='text-warning fa fa-warning'></i> Warning! This will reset all
				your widget settings." data-html="true"><i class="fa fa-refresh"></i></span>
		</span>

		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>用户管理</li>
            <li>用户详情</li>
		</ol>
		<!-- end breadcrumb -->

	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					<i class="fa fa-list-alt"></i> 用户管理 <span>> 用户详情</span>
				</h1>
			</div>
	    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8"
                 style="display: block;">

                <div class="col-sm-14 text-align-right" style="width: 100%;margin-top:15px;">

                    <div class="btn-group">
                        <a href="index.php?m=admin&c=user&a=index" class="btn btn-sm bg-color-red txt-color-white"
                           style="padding-left: 15px;"><i
                                class="glyphicon glyphicon-list"> </i> 用户列表</a>
                    </div>

                </div>

            </div>
		</div>
		<!-- widget grid -->
		<section id="widget-grid" class="">

			<div class="row">

				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-user-list--detail"
						data-widget-editbutton="true" data-widget-sortable="true" data-widget-fullscreenbutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-table"></i></span>
							<h2 style="line-height: 30px;">用户详情</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body no-padding">
								<div class="widget-body-toolbar">
                                  
                                <div class="row" style="width: 100%;margin:0 auto;">
						            
                                    
                                    
                                    
                                
				
													<div class="col-sm-6">
				
														 
													 
				
															 
                                            <fieldset>
												<legend>
													基本信息
												</legend>
				
												<div class="row">
													<div class="col-sm-12">
														<div class="col-sm-2">客户ID：<{$user->id}></div>
                                                        <div class="col-sm-3">注册电话：<{$user->phone}></div>
                                                        <div class="col-sm-3">注册时间：<{date('Y-m-d H:i',$user->created_at)}></div>
													</div>
												</div>
											</fieldset>
                                            
                                            <fieldset>
												<legend>
													订阅信息
												</legend>
				
												<div class="row">
													<div class="col-sm-12" style="padding-right:0px;">
														<div class="col-sm-10"><{getUserSubscribe($user->id)}></div> 
                                                        <div class="col-sm-2"><a class="btn btn-info btn-xs" href="index.php?m=admin&c=user&a=browers&id=<{$user->id}>" style="float:right;">浏览记录</a></div> 
													</div>
				
												</div>
											</fieldset>
                                            
                                            
                                            <fieldset>
												<legend>
													信息备注
												</legend>
				<form id="order-form" class="smart-form" novalidate="novalidate">
												<div class="row" style="width: 99%;margin: 0 auto;">
													<div class="col-sm-12">
														<div class="form-group">
                                                            <textarea class="form-control" placeholder="信息备注" id="remark" name="remark" rows="3" style="padding:5px;"></textarea>
                                                        </div>
													</div>
                                                    <footer style="width:99%;">
                                                        <button type="button" class="btn btn-primary" id="btnRemark">
                                                            保存
                                                        </button><h1 id="loading" style="display: none;margin-left:35px;"><i class="fa fa-cog fa-spin"></i> Loading...</h1>
                                                    </footer>
                </form>
												 
				
												</div>
											</fieldset>
                                                             
                                                             
				
												 
													</div>
				
													<div class="col-sm-6">
														  <fieldset>
                                                            <legend>
                                                                客户跟进信息
                                                            </legend>
                            
                                                            <div class="row">
                                                                
															<{foreach $remarks as $rr}>	
																
                                                                <div class="col-sm-12" style="margin-bottom:10px;">
                                                                    <div class="col-sm-2"><{date('Y-m-d H:i',$rr->created_at)}></div>
                                                                    <div class="col-sm-8">
                                                                        
                                                                       <{$rr->remark}>
                                                                        
                                                                    </div>
                                                                </div>
                                                            <{foreachelse}>
																<div class="col-sm-12" style="margin-bottom:10px;">
																	没有备注
																</div>
															<{/foreach}>	
                                                                
                                                                
                                                            </div>
                                                        </fieldset>
													</div>
				
									 
                                    
                                    
                                    
                                    
                                    
                                </div>	
									
							</div>

								 
							</div>
							<!-- end widget content -->

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->
				</article>

			</div>


		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->

</div>

	</body>
</html>		<!-- END SHORTCUT AREA -->

		<!--================================================== -->

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
		<script data-pace-options='{ "restartOnRequestAfter": true }' src="/resources/js/plugin/pace/pace.min.js"></script>

		<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
		<script>
			if (!window.jQuery) {
				document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
			}
		</script>
		<script>
			if (!window.jQuery.ui) {
				document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
			}
		</script>
		<script src="/resources/js/jquery.alerts.js" type="text/javascript"></script>
		<link href="/resources/css/jquery.alerts.css" rel="stylesheet" type="text/css" media="screen" />
		<script src="/resources/js/jquery.form.js"></script>
		<script src="/resources/js/jquery.validate.js"></script>
		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
		<script src="/resources/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->
		<script src="/resources/js/bootstrap/bootstrap.min.js"></script>

		<!-- CUSTOM NOTIFICATION -->
		<script src="/resources/js/notification/SmartNotification.min.js"></script>

		<!-- JARVIS WIDGETS -->
		<script src="/resources/js/smartwidgets/jarvis.widget.min.js"></script>

		<!-- EASY PIE CHARTS -->
		<script src="/resources/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

		<!-- SPARKLINES -->
		<script src="/resources/js/plugin/sparkline/jquery.sparkline.min.js"></script>

		<!-- JQUERY VALIDATE -->
		<script src="/resources/js/plugin/jquery-validate/jquery.validate.min.js"></script>

		<!-- JQUERY MASKED INPUT -->
		<script src="/resources/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

		<!-- JQUERY SELECT2 INPUT -->
		<script src="/resources/js/plugin/select2/select2.min.js"></script>

		<!-- JQUERY UI + Bootstrap Slider -->
		<script src="/resources/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

		<!-- browser msie issue fix -->
		<script src="/resources/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

		<!-- FastClick: For mobile devices -->
		<script src="/resources/js/plugin/fastclick/fastclick.js"></script>

		<!--[if IE 7]>

		<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

		<![endif]-->
		<!-- MAIN APP JS FILE -->
		<script src="/resources/js/app.js"></script>
		<script src="/resources/js/demo.js"></script>

		<!-- PAGE RELATED PLUGIN(S) -->
		
 
	   <!-- PAGE RELATED PLUGIN(S) -->
		<script src="/resources/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
		<script src="/resources/js/plugin/datatables/ColReorder.min.js"></script>
		<script src="/resources/js/plugin/datatables/FixedColumns.min.js"></script>
		<script src="/resources/js/plugin/datatables/ColVis.min.js"></script>
		<script src="/resources/js/plugin/datatables/ZeroClipboard.js"></script>
		<script src="/resources/js/plugin/datatables/media/js/TableTools.min.js"></script>
		<script src="/resources/js/plugin/datatables/DT_bootstrap.js"></script>
        <script src="/resources/layer_mobile/layer.js?2.x"></script>
		

		<script type="text/javascript">
		
        function isNull(str) {
			if (str == "") return true;
			var regu = "^[ ]+$";
			var re = new RegExp(regu);
			return re.test(str);
		}
        
		$(document).ready(function() {
            
            $.datepicker.regional["zh-CN"] = { closeText: "关闭",currentText: "今天", monthNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], dayNames: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"], dayNamesShort: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"], dayNamesMin: ["日", "一", "二", "三", "四", "五", "六"], weekHeader: "周", dateFormat: "yy-mm-dd", firstDay: 1, isRTL: !1, showMonthAfterYear: !0, yearSuffix: "年" }
            $.datepicker.setDefaults($.datepicker.regional["zh-CN"]);
            pageSetUp();
            $('.date').datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,  
                changeMonth: true,
                changeYear: true,
                prevText : '<i class="fa fa-chevron-left"></i>',
                nextText : '<i class="fa fa-chevron-right"></i>',
                dateFormat : 'yy-mm-dd'
            });
			
			$("#btnRemark").click(function(){
				var user_id = "<{$user->id}>";
				var remark = $("#remark").val();
				
				if(isNull(remark)){
					layer.open({
						 content: '信息备注不能为空'
						,btn: '确定'
					});
					
					return false;
				}
				
				layer.open({
					type: 2,
					content: '加载中'
				}); 
							 
				
				$.ajax({  
                    type:"POST",  
                    async:false,  
                    url:"index.php?m=admin&c=user&a=doremark",  
                    data:{
                        user_id:user_id,
                        remark:remark
                    },
                    dataType:'json',  
                    success:function(data){
                                           
                        layer.closeAll();
                       if(data.status==1){
                         
						
						  nbox("操作成功",1);
						  setTimeout(function(){
							 window.location.reload(); 
							},2000);
                               
                       }else if(data.status==0){
                          nbox( data.msg ,0);
                       }                         
                                
                   }
                });
				 
				 
			});
            
			 
		});

 </script>
 
