<!DOCTYPE html>
<html lang="en-us">
	<head>
		<meta charset="utf-8">
		<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

		<title> 魔方铺源(管理工具) </title>
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/font-awesome.min.css">

		<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-production.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-skins.css">

		<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

		<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/demo.css">

		<!-- FAVICONS -->
		<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">

		<!-- GOOGLE FONT -->
		<link rel="stylesheet" href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">

	</head>
	<body class="">
<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- RIBBON -->
	<div id="ribbon">

		<span class="ribbon-button-alignment"> <span id="refresh"
			class="btn btn-ribbon" data-title="refresh" rel="tooltip"
			data-placement="bottom" data-original-title="<i 
			class='text-warning fa fa-warning'></i> Warning! This will reset all
				your widget settings." data-html="true"><i class="fa fa-refresh"></i></span>
		</span>

		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>用户管理</li>
		</ol>
		<!-- end breadcrumb -->

	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					<i class="fa fa-list-alt"></i> 用户管理 <span>> 数据列表</span>
				</h1>
			</div>
	    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8"
                 style="display: block;">

                <div class="col-sm-14 text-align-right" style="width: 100%;margin-top:15px;">

                    <div class="btn-group">
                        <a href="index.php?m=admin&c=user&a=index" class="btn btn-sm bg-color-red txt-color-white"
                           style="padding-left: 15px;"><i
                                class="glyphicon glyphicon-list"> </i> 用户列表</a>
                    </div>

                </div>

            </div>
		</div>
		<!-- widget grid -->
		<section id="widget-grid" class="">

			<div class="row">

				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-user-list"
						data-widget-editbutton="true" data-widget-sortable="true" data-widget-fullscreenbutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-table"></i></span>
							<h2 style="line-height: 30px;">数据列表</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body no-padding">
								<div class="widget-body-toolbar">
                                  
                                <div class="row" style="width: 100%;margin:0 auto;">
                                       
						            <form id="s_form" method="GET" class="smart-form" action="index.php?m=admin&c=user&a=index">
						               <fieldset style="padding-left: 5px;">
						            		 
                                            
                                            <section class="col col-12" style="width:160px;float:left;padding-left:0;">
													<label class="input"> <i class=""></i>
																	<input type="text" value="<{$s_userid}>" name="s_userid" id="s_userid" placeholder="用户ID">
																	</label>
										    </section>
                                            
                                            <section class="col col-12" style="width:200px;float:left;padding-left:0;">
													<label class="input"> <i class=""></i>
																	<input type="text" value="<{$s_phone}>" name="s_phone" id="s_phone" placeholder="手机号码">
																	</label>
										    </section>
										     				     
										     <a id="btnSearch" style="margin-top:1px;" href="javascript:void(0);" class="btn  btn-sm btn-primary"><i class="glyphicon glyphicon-search"></i>搜索</a>
										 </fieldset>
                                         <input type="hidden" name="m" value="admin" />
										 <input type="hidden" name="c" value="user" />
										 <input type="hidden" name="a" value="index" />
                                         
                                         <input type="hidden" name="sortField" id="sortField" value="<{$sortField}>" />
                                         <input type="hidden" name="sortValue" id="sortValue" value="<{$sortValue}>" />
                                         
                                    </form>   
                                </div>	
									
							</div>

								<table id="dt_basic"
									class="table table-striped table-bordered table-hover" style="width:99%;margin:0 auto;">                                    
									<tbody>
									 	 
                                    <tr>
                                       <th style="width: 60px;cursor: pointer;" id="id_px">用户ID
                                       <{if $sortField eq 'id' && $sortValue eq 'asc'}>
                                       ⇧
                                       <{elseif  $sortField eq 'id' && $sortValue eq 'desc'}>
                                       ⇩
                                       <{/if}>
                                       </th>
                                       <th style="width:140px;">注册电话</th>
                                       <th style="width: 140px;cursor: pointer;" id="created_at_px">注册时间
                                       
                                       <{if $sortField eq 'created_at' && $sortValue eq 'asc'}>
                                       ⇧
                                       <{elseif  $sortField eq 'created_at' && $sortValue eq 'desc'}>
                                       ⇩
                                       <{/if}>
                                       </th>
                                       <th style="width: 340px;">订阅内容</th>
                                       <th style="width: 160px;cursor: pointer;" id="brower_today_px">全网浏览量  今日
                                       <{if $sortField eq 'brower_today' && $sortValue eq 'asc'}>
                                       ⇩
                                       <{elseif  $sortField eq 'brower_today' && $sortValue eq 'desc'}>
                                       ⇧
                                       <{/if}>
                                       </th>
                                       <th style="width: 160px;cursor: pointer;" id="brower_seven_px">全网浏览量  近七日
                                       <{if $sortField eq 'brower_seven' && $sortValue eq 'asc'}>
                                       ⇧
                                       <{elseif  $sortField eq 'brower_seven' && $sortValue eq 'desc'}>
                                       ⇩
                                       <{/if}>
                                       </th>
                                       <th style="width: 80px;">操作</th>
                                    </tr>
                                    
                                    
                                    <{foreach from=$lists item=vo}>
                                         <tr>
                                            <td style="width: 60px;"><{$vo['id']}></td>
                                            <td style="width:140px;"><{$vo['phone']}></td>
                                            <td style="width: 140px;"><{$vo['created_at']}></td>
                                            <td style="width: 340px;"><{$vo['subscribe']}></td>
                                            <td style="width: 160px;"><{$vo['brower_today']}></td>
                                            <td style="width: 160px;"><{$vo['brower_seven']}></td>
                                            <td>
                                            <a class="btn btn-info btn-xs" href="index.php?m=admin&amp;c=user&amp;a=detail&amp;id=<{$vo['id']}>"><i class="fa fa-file-text"></i> 查看详情 </a>
                                            </td>
                                         </tr>
                                        
                                    <{foreachelse}>
    										<tr>
    										<td colspan="7">暂无</td>
    										</tr>
    								<{/foreach}>	    
                                         
                                         
									</tbody>
									
								</table>
								<div class="text-center">
								<ul class="pagination pagination-alt">
                                    <{if $totalRecords gt 10}>
										 <{$pages}>
                                    <{/if}>        
								</ul></div>
							</div>
							<!-- end widget content -->

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->
				</article>

			</div>


		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->

</div>

	</body>
</html>		<!-- END SHORTCUT AREA -->

		<!--================================================== -->

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
		<script data-pace-options='{ "restartOnRequestAfter": true }' src="/resources/js/plugin/pace/pace.min.js"></script>

		<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
		<script>
			if (!window.jQuery) {
				document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
			}
		</script>
		<script>
			if (!window.jQuery.ui) {
				document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
			}
		</script>
		<script src="/resources/js/jquery.alerts.js" type="text/javascript"></script>
		<link href="/resources/css/jquery.alerts.css" rel="stylesheet" type="text/css" media="screen" />
		<script src="/resources/js/jquery.form.js"></script>
		<script src="/resources/js/jquery.validate.js"></script>
		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
		<script src="/resources/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->
		<script src="/resources/js/bootstrap/bootstrap.min.js"></script>

		<!-- CUSTOM NOTIFICATION -->
		<script src="/resources/js/notification/SmartNotification.min.js"></script>

		<!-- JARVIS WIDGETS -->
		<script src="/resources/js/smartwidgets/jarvis.widget.min.js"></script>

		<!-- EASY PIE CHARTS -->
		<script src="/resources/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

		<!-- SPARKLINES -->
		<script src="/resources/js/plugin/sparkline/jquery.sparkline.min.js"></script>

		<!-- JQUERY VALIDATE -->
		<script src="/resources/js/plugin/jquery-validate/jquery.validate.min.js"></script>

		<!-- JQUERY MASKED INPUT -->
		<script src="/resources/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

		<!-- JQUERY SELECT2 INPUT -->
		<script src="/resources/js/plugin/select2/select2.min.js"></script>

		<!-- JQUERY UI + Bootstrap Slider -->
		<script src="/resources/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

		<!-- browser msie issue fix -->
		<script src="/resources/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

		<!-- FastClick: For mobile devices -->
		<script src="/resources/js/plugin/fastclick/fastclick.js"></script>

		<!--[if IE 7]>

		<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

		<![endif]-->
		<!-- MAIN APP JS FILE -->
		<script src="/resources/js/app.js"></script>
		<script src="/resources/js/demo.js"></script>

		<!-- PAGE RELATED PLUGIN(S) -->
		
 
	   <!-- PAGE RELATED PLUGIN(S) -->
		<script src="/resources/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
		<script src="/resources/js/plugin/datatables/ColReorder.min.js"></script>
		<script src="/resources/js/plugin/datatables/FixedColumns.min.js"></script>
		<script src="/resources/js/plugin/datatables/ColVis.min.js"></script>
		<script src="/resources/js/plugin/datatables/ZeroClipboard.js"></script>
		<script src="/resources/js/plugin/datatables/media/js/TableTools.min.js"></script>
		<script src="/resources/js/plugin/datatables/DT_bootstrap.js"></script>
        
		

		<script type="text/javascript">
		
        function isNull(str) {
			if (str == "") return true;
			var regu = "^[ ]+$";
			var re = new RegExp(regu);
			return re.test(str);
		}
        
		$(document).ready(function() {
            
            $("#btnSearch").click(function(){
					$("#s_form").attr('action',"index.php?m=admin&c=user&a=index"); 
					$("#s_form").submit(); 		
	        });
            
            //id_px
            $("#id_px").click(function(){
                   var sortField = $("#sortField").val();
                   var sortValue = $("#sortValue").val();
                   
                   
                   if(sortValue=="asc"){
                        $("#sortValue").val("desc");
                        sortValue="desc";
                   }else{
                        $("#sortValue").val("asc");
                        sortValue="asc";
                   }
                   
                   $("#sortField").val( 'id' );
                   $("#sortValue").val( sortValue );
                   
                   $("#s_form").attr('action',"index.php?m=admin&c=user&a=index"); 
				   $("#s_form").submit(); 	
                
            });
            
            $("#created_at_px").click(function(){
                   var sortField = $("#sortField").val();
                   var sortValue = $("#sortValue").val();
                   
                   
                   if(sortValue=="asc"){
                        $("#sortValue").val("desc");
                        sortValue="desc";
                   }else{
                        $("#sortValue").val("asc");
                        sortValue="asc";
                   }
                   
                   $("#sortField").val( 'created_at' );
                   $("#sortValue").val( sortValue );
                   
                   $("#s_form").attr('action',"index.php?m=admin&c=user&a=index"); 
				   $("#s_form").submit(); 	
                
            });
            
            
            $("#brower_today_px").click(function(){
                   var sortField = $("#sortField").val();
                   var sortValue = $("#sortValue").val();
                   
                   
                   if(sortValue=="asc"){
                        $("#sortValue").val("desc");
                        sortValue="desc";
                   }else{
                        $("#sortValue").val("asc");
                        sortValue="asc";
                   }
                   
                   $("#sortField").val( 'brower_today' );
                   $("#sortValue").val( sortValue );
                   
                   $("#s_form").attr('action',"index.php?m=admin&c=user&a=index"); 
				   $("#s_form").submit(); 	
            });
            
            $("#brower_seven_px").click(function(){
                   var sortField = $("#sortField").val();
                   var sortValue = $("#sortValue").val();
                   
                   
                   if(sortValue=="asc"){
                        $("#sortValue").val("desc");
                        sortValue="desc";
                   }else{
                        $("#sortValue").val("asc");
                        sortValue="asc";
                   }
                   
                   $("#sortField").val( 'brower_seven' );
                   $("#sortValue").val( sortValue );
                   
                   $("#s_form").attr('action',"index.php?m=admin&c=user&a=index"); 
				   $("#s_form").submit(); 	
            });
            
            
            $.datepicker.regional["zh-CN"] = { closeText: "关闭",currentText: "今天", monthNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], dayNames: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"], dayNamesShort: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"], dayNamesMin: ["日", "一", "二", "三", "四", "五", "六"], weekHeader: "周", dateFormat: "yy-mm-dd", firstDay: 1, isRTL: !1, showMonthAfterYear: !0, yearSuffix: "年" }
            $.datepicker.setDefaults($.datepicker.regional["zh-CN"]);
            pageSetUp();
            $('.date').datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,  
                changeMonth: true,
                changeYear: true,
                prevText : '<i class="fa fa-chevron-left"></i>',
                nextText : '<i class="fa fa-chevron-right"></i>',
                dateFormat : 'yy-mm-dd'
            });
            
			 
		});

 </script>
 
