<!DOCTYPE html>
<html lang="en-us">
<head>
<meta charset="utf-8">
<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

<title>铺军师(管理工具)</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->

<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Basic Styles -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/font-awesome.min.css">

<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-production.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-skins.css">

<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/demo.css">

<!-- FAVICONS -->
<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">
<link rel="icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">

<!-- GOOGLE FONT -->
<link rel="stylesheet"
	href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/js/libs/jquery-ui-timepicker-addon.css">
</head>
<body class="">
	<script>
    if (!window.jQuery) {
        document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
    }
</script>

	<script>
    if (!window.jQuery.ui) {
        document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
    }
</script>
<form id="form1" method="post" class="smart-form">
									<!-- widget content -->
									<div
										class="sortable-grid ui-sortable col-xs-12"
										style="float: left;width:99%;">

 
<div
										class="col-xs-12  sortable-grid ui-sortable"
										style="">

										<fieldset>
											 
											<section>
                                                <div class="inline-group">
                                                    <label class="radio">
                                                        <input type="radio" name="status" value="0" <{if $store->status eq 0}> checked <{/if}> >
                                                        <i></i>转租中</label>
                                                    <label class="radio">
                                                        <input type="radio" name="status" value="1" <{if $store->status eq 1}> checked <{/if}> >
                                                        <i></i>已出租</label>
                                                    <label class="radio">
                                                        <input type="radio" name="status" value="2" <{if $store->status eq 2}> checked <{/if}> >
                                                        <i></i>已删除</label>
                                                </div>
                                            </section>
            								
												 

											<div class="col-sm-12 col-md-12 sortable-grid ui-sortable">
										<footer style="margin-bottom: 30px;">
											<button id="btnSubmit" type="button" class="btn btn-primary">
												提 交</button>
											<button id="btnClose"  type="button" class="btn btn-default">取 消</button>
										</footer>
									</div>
										 </fieldset>


									</div>
									</div></form></body>

<script>
function isNull(str) {
    if (str == "") return true;
    var regu = "^[ ]+$";
    var re = new RegExp(regu);
    return re.test(str);
}

$(function(){

	$("#btnClose").click(function(){
		parent.closeLayer(); 
	});
			
	$("#btnSubmit").click(function(){
        var store_id = "<{$store->id}>";
        var status = $("input[name='status']:checked").val();
		parent.doChangeStatus(store_id,status);
		return false;    
	});
	 
	
})


</script>