<!DOCTYPE html>
<html lang="en-us">
	<head>
		<meta charset="utf-8">
		<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
		<title> 蚂蚁(管理工具) </title>
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<!-- Basic Styles -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/font-awesome.min.css">

		<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-production.css">
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-skins.css">

		<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

		<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

		<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/demo.css">

		<!-- FAVICONS -->
		<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/resources/img/favicon/favicon.ico" type="image/x-icon">

		<!-- GOOGLE FONT -->
		<link rel="stylesheet" href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">
		<style>
.jarviswidget-color-darken > header > .jarviswidget-ctrls a, .jarviswidget-color-darken .nav-tabs li:not(.active) a {
    color: rgb(0, 0, 0);
}
        </style>	
        
        <link href="/resources/lightGallery/dist/css/lightgallery.css" rel="stylesheet">
        <style type="text/css">
            body{
                background-color: #152836
            }
            .demo-gallery > ul {
              margin-bottom: 0;
            }
            .demo-gallery > ul > li {
                float: left;
                margin-bottom: 15px;
                margin-right: 20px;
                width: 200px;
            }
            .demo-gallery > ul > li a {
              border: 3px solid #FFF;
              border-radius: 3px;
              display: block;
              overflow: hidden;
              position: relative;
              float: left;
            }
            .demo-gallery > ul > li a > img {
              -webkit-transition: -webkit-transform 0.15s ease 0s;
              -moz-transition: -moz-transform 0.15s ease 0s;
              -o-transition: -o-transform 0.15s ease 0s;
              transition: transform 0.15s ease 0s;
              -webkit-transform: scale3d(1, 1, 1);
              transform: scale3d(1, 1, 1);
              height: 100%;
              width: 100%;
            }
            .demo-gallery > ul > li a:hover > img {
              -webkit-transform: scale3d(1.1, 1.1, 1.1);
              transform: scale3d(1.1, 1.1, 1.1);
            }
            .demo-gallery > ul > li a:hover .demo-gallery-poster > img {
              opacity: 1;
            }
            .demo-gallery > ul > li a .demo-gallery-poster {
              background-color: rgba(0, 0, 0, 0.1);
              bottom: 0;
              left: 0;
              position: absolute;
              right: 0;
              top: 0;
              -webkit-transition: background-color 0.15s ease 0s;
              -o-transition: background-color 0.15s ease 0s;
              transition: background-color 0.15s ease 0s;
            }
            .demo-gallery > ul > li a .demo-gallery-poster > img {
              left: 50%;
              margin-left: -10px;
              margin-top: -10px;
              opacity: 0;
              position: absolute;
              top: 50%;
              -webkit-transition: opacity 0.3s ease 0s;
              -o-transition: opacity 0.3s ease 0s;
              transition: opacity 0.3s ease 0s;
            }
            .demo-gallery > ul > li a:hover .demo-gallery-poster {
              background-color: rgba(0, 0, 0, 0.5);
            }
            .demo-gallery .justified-gallery > a > img {
              -webkit-transition: -webkit-transform 0.15s ease 0s;
              -moz-transition: -moz-transform 0.15s ease 0s;
              -o-transition: -o-transform 0.15s ease 0s;
              transition: transform 0.15s ease 0s;
              -webkit-transform: scale3d(1, 1, 1);
              transform: scale3d(1, 1, 1);
              height: 100%;
              width: 100%;
            }
            .demo-gallery .justified-gallery > a:hover > img {
              -webkit-transform: scale3d(1.1, 1.1, 1.1);
              transform: scale3d(1.1, 1.1, 1.1);
            }
            .demo-gallery .justified-gallery > a:hover .demo-gallery-poster > img {
              opacity: 1;
            }
            .demo-gallery .justified-gallery > a .demo-gallery-poster {
              background-color: rgba(0, 0, 0, 0.1);
              bottom: 0;
              left: 0;
              position: absolute;
              right: 0;
              top: 0;
              -webkit-transition: background-color 0.15s ease 0s;
              -o-transition: background-color 0.15s ease 0s;
              transition: background-color 0.15s ease 0s;
            }
            .demo-gallery .justified-gallery > a .demo-gallery-poster > img {
              left: 50%;
              margin-left: -10px;
              margin-top: -10px;
              opacity: 0;
              position: absolute;
              top: 50%;
              -webkit-transition: opacity 0.3s ease 0s;
              -o-transition: opacity 0.3s ease 0s;
              transition: opacity 0.3s ease 0s;
            }
            .demo-gallery .justified-gallery > a:hover .demo-gallery-poster {
              background-color: rgba(0, 0, 0, 0.5);
            }
            .demo-gallery .video .demo-gallery-poster img {
              height: 48px;
              margin-left: -24px;
              margin-top: -24px;
              opacity: 0.8;
              width: 48px;
            }
            .demo-gallery.dark > ul > li a {
              border: 3px solid #04070a;
            }
            .home .demo-gallery {
              padding-bottom: 80px;
            }
.lg-actions .lg-prev {
    left: 220px;
}
.lg-outer .lg-thumb {
    height: 100%;
    margin-bottom: 5px;
    padding: 10px 0px;
	margin-left:220px;
}
.lg-outer {
	bottom:20px;
}

.lg-outer .lg-thumb-outer {
	bottom:40px;
}
        </style>
    
	<link rel="stylesheet" href="https://cache.amap.com/lbs/static/main1119.css"/>
    <script src="http://cache.amap.com/lbs/static/es5.min.js"></script>
    <script src="http://webapi.amap.com/maps?v=1.4.0&amp;key=0990c546f2f65aad75220acb10e2d4b9&plugin=AMap.Scale,AMap.OverView,AMap.ToolBar,aMap.Driving"></script>
    <script type="text/javascript" src="http://cache.amap.com/lbs/static/addToolbar.js"></script>
        
	</head>
	<body class="" style="height: 2200px;">
<!-- MAIN PANEL -->
<div id="main" role="main" >

	<!-- RIBBON -->
	<div id="ribbon">

		<span class="ribbon-button-alignment"> <span id="refresh"
			class="btn btn-ribbon" data-title="refresh" rel="tooltip"
			data-placement="bottom" data-original-title="<i 
			class='text-warning fa fa-warning'></i> Warning! This will reset all
				your widget settings." data-html="true"><i class="fa fa-refresh"></i></span>
		</span>

		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>铺源管理</li>
            <li>魔方铺源</li>
		</ol>
		<!-- end breadcrumb -->

	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					<i class="fa fa-list-alt"></i> 魔方铺源 <span>> 铺源详情</span>
				</h1>
			</div>
	    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8"
                 style="display: block;">

                <div class="col-sm-14 text-align-right" style="width: 100%;margin-top:15px;">

                    <div class="btn-group">
                        <a href="javascript:void(0)" class="btn btn-sm bg-color-green txt-color-white"
                           style="padding-left: 15px;"><{$status_str}></a>
                    </div> 
                       
                    <div class="btn-group">
                        <a href="index.php?m=admin&c=store&a=updateStore&id=<{$store->id}>" class="btn btn-sm bg-color-blue txt-color-white"
                           style="padding-left: 15px;"><i class="fa fa-edit"></i>  修改商铺</a>
                    </div>
                    
                    <div class="btn-group">
                        <a href="index.php?m=admin&c=store&a=store" class="btn btn-sm bg-color-red txt-color-white"
                           style="padding-left: 15px;"><i
                                class="glyphicon glyphicon-list"> </i> 店铺列表</a>
                    </div> 
                      
                </div>

            </div>
		</div>
		<!-- widget grid -->
		<section id="widget-grid" class="">

			<div class="row" style="height: 1600px;">

				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-store-detail"
						data-widget-editbutton="true" data-widget-sortable="true" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
						<!-- widget options:
								usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
				
								data-widget-colorbutton="false"
								data-widget-editbutton="false"
								data-widget-togglebutton="false"
								data-widget-deletebutton="false"
								data-widget-fullscreenbutton="false"
								data-widget-custombutton="false"
								data-widget-collapsed="true"
								data-widget-sortable="false"
				
								-->
						<header>
							<span class="widget-icon"> <i class="fa fa-table"></i></span>
							<h2 style="line-height: 30px;">店铺详情</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body no-padding">
							
                            	<table class="table table-bordered table-striped table-hover" style="width:98%;margin:0 auto;margin-top:20px;">
									<tbody>
                                        
                                        <tr>
											<td style="line-height: 30px;font-size:14px;">
											<span style="line-height: 25px;font-size:14px;">
											 <span><{$store->district}> - <{$store->street}><{$store->street_sn}>号</span>
                                             <span style="margin-left:200px;"><{$contacts}></span>
											</span>
											
											</td>
										</tr>
                                        
										<tr style="background: #fff;">
											<td>
                                                <div id="mapInfo" style="line-height: 400px;height: 400px;width: 100%;">
                                                 
                                                </div>
											</td>
										</tr>
										
										<tr>
											<td style="line-height: 30px;font-size:14px;">
                                                
											<span style="line-height: 25px;font-size:14px;">
											   <{$store->present_operation}> （<{$store->trade}>），
                                               <{$store->property}>，
                                               共<{$store->floor_total}>层，第<{$store->floor_start}>层~第<{$store->floor_end}>层。
                                               建筑面积<{$store->build_area}>平方米，使用面积<{$store->use_area}>平方米。
											</span>
                                            <br>
                                            <span style="line-height: 25px;font-size:14px;clear: both;">
											   门头宽度<{$store->door_width}>米，
                                               配套有<{$installation_str}>。
                                               租金<{$store->rental_year}>万/年，转让费<{$store->transfer_fee}>万/年，
                                               压<{$store->payment_deposit}>付<{$store->payment_pay}>，
                                               剩余租期<{$store->residual_lease}>个月，<{$store->charge_remark}>。
                                               
											</span>
											
											</td>
										</tr>
										
										<tr>
											<td>
												  <span>
    											   标签：
                                                  <{foreach $tags as $tag}>
                                                    <{$tag}>
                                                  <{/foreach}>  
    											  </span>
											</td>
										</tr>
										 
										<tr>
											<td>
											<span>图片</span>
											 
											 	<div class="dropzone dz-clickable dz-started" id="swap_thumb" style="min-height: 120px;" >
                                        			 
                                        			  <ul id="lightgallery" class="list-unstyled row">
                                        			   <{foreach $thumbs as $thumb}>				
                                                            <li class="dz-preview dz-processing dz-success dz-image-preview" data-responsive="" data-src="<{$thumb['original_url']}>" data-sub-html="<h4></h4><p></p>">
                                                                <a href="">
                                                                    <img class="img-responsive" src="<{$thumb['thumb_url']}>">
                                                                </a>
                                                            </li>
                                                        <{/foreach}>		    
                                                             
                                                        </ul>
                                        			 
											 	</div>
											  
									
											</td>
										</tr> 
									</tbody>
								 </table>
								  

							 
							<!-- end widget content -->

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->
				</article>

			</div>


		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->

</div>

	</body>
</html>		<!-- END SHORTCUT AREA -->

		<!--================================================== -->

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
		<script data-pace-options='{ "restartOnRequestAfter": true }' src="/resources/js/plugin/pace/pace.min.js"></script>

		<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
		<script>
			if (!window.jQuery) {
				document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
			}
		</script>
		<script>
			if (!window.jQuery.ui) {
				document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
			}
		</script>
		<script src="/resources/js/jquery.alerts.js" type="text/javascript"></script>
		<link href="/resources/css/jquery.alerts.css" rel="stylesheet" type="text/css" media="screen" />
		<script src="/resources/js/jquery.form.js"></script>
		<script src="/resources/js/jquery.validate.js"></script>
		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
		<script src="/resources/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->
		<script src="/resources/js/bootstrap/bootstrap.min.js"></script>

		<!-- CUSTOM NOTIFICATION -->
		<script src="/resources/js/notification/SmartNotification.min.js"></script>

		<!-- JARVIS WIDGETS -->
		<script src="/resources/js/smartwidgets/jarvis.widget.min.js"></script>

		<!-- EASY PIE CHARTS -->
		<script src="/resources/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

		<!-- SPARKLINES -->
		<script src="/resources/js/plugin/sparkline/jquery.sparkline.min.js"></script>

		<!-- JQUERY VALIDATE -->
		<script src="/resources/js/plugin/jquery-validate/jquery.validate.min.js"></script>

		<!-- JQUERY MASKED INPUT -->
		<script src="/resources/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

		<!-- JQUERY SELECT2 INPUT -->
		<script src="/resources/js/plugin/select2/select2.min.js"></script>

		<!-- JQUERY UI + Bootstrap Slider -->
		<script src="/resources/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

		<!-- browser msie issue fix -->
		<script src="/resources/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

		<!-- FastClick: For mobile devices -->
		<script src="/resources/js/plugin/fastclick/fastclick.js"></script>

		<!--[if IE 7]>

		<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

		<![endif]-->
		<!-- MAIN APP JS FILE -->
		<script src="/resources/js/app.js"></script>

		<!-- PAGE RELATED PLUGIN(S) -->
		
 
	   <!-- PAGE RELATED PLUGIN(S) -->
		<script src="/resources/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
		<script src="/resources/js/plugin/datatables/ColReorder.min.js"></script>
		<script src="/resources/js/plugin/datatables/FixedColumns.min.js"></script>
		<script src="/resources/js/plugin/datatables/ColVis.min.js"></script>
		<script src="/resources/js/plugin/datatables/ZeroClipboard.js"></script>
		<script src="/resources/js/plugin/datatables/media/js/TableTools.min.js"></script>
		<script src="/resources/js/plugin/datatables/DT_bootstrap.js"></script>
        <script src="/resources/layer/layer.js"></script>
        
        <script src="https://cdn.jsdelivr.net/picturefill/2.3.1/picturefill.min.js"></script>
        <script src="/resources/lightGallery/dist/js/lightgallery.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-fullscreen.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-thumbnail.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-video.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-autoplay.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-zoom.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-hash.js"></script>
        <script src="/resources/lightGallery/demo/js/lg-pager.js"></script>
        <script src="/resources/lightGallery/lib/jquery.mousewheel.min.js"></script>
		

<script type="text/javascript">
	
	
	var map = new AMap.Map('mapInfo', {
        resizeEnable: true,
        zoom: 15,
        center: [<{$store->location_lng}>,<{$store->location_lat}>],
        mapStyle: 'amap://styles/fresh'
    });
	
	
	function Move(map, coordinate, title) {
        var marker = new AMap.Marker({
            position: coordinate || null,//marker所在的位置
            //icon: 'http://ozc9gamh2.bkt.clouddn.com/web1511311658864?imageView2/1/w/100/h/100',//自定义的图片
            title: title,
            animation: 'AMAP_ANIMATION_DROP',//marker的动画效果
            draggable: false,//是否可可移动
            raiseOnDrag: false,//拖拽点离开地图的效果
            map: map//创建时直接赋予map属性
        });
        /*var _onClick = function (e) {
            console.log(e)
            console.log(e.target.F.title)
        }
        AMap.event.addListener(marker, 'click', _onClick)*/

        //鼠标点击marker弹出自定义的信息窗体
        AMap.event.addListener(marker, 'click', function() {
            infoWindow.open(map, marker.getPosition());
        });
    }

    Move(map, [<{$store->location_lng}>,<{$store->location_lat}>], "<{$store->district}> - <{$store->street}><{$store->street_sn}>号");

	
	
	
$(document).ready(function() {
	$('#lightgallery').lightGallery();
    $.datepicker.regional["zh-CN"] = { closeText: "关闭",currentText: "今天", monthNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], dayNames: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"], dayNamesShort: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"], dayNamesMin: ["日", "一", "二", "三", "四", "五", "六"], weekHeader: "周", dateFormat: "yy-mm-dd", firstDay: 1, isRTL: !1, showMonthAfterYear: !0, yearSuffix: "年" }
    $.datepicker.setDefaults($.datepicker.regional["zh-CN"]);
    pageSetUp();
    $('.date').datepicker({
        showOtherMonths: true,
        selectOtherMonths: true,  
        changeMonth: true,
        changeYear: true,
        prevText : '<i class="fa fa-chevron-left"></i>',
        nextText : '<i class="fa fa-chevron-right"></i>',
        dateFormat : 'yy-mm-dd'
    });
 
});

 </script>
 
