<!DOCTYPE html>
<html lang="en-us">
<head>
<meta charset="utf-8">
<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

<title>铺军师(管理工具)</title>
<meta name="description" content="">
<meta name="author" content="">
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
     
<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->

<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Basic Styles -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/font-awesome.min.css">

<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-production.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-skins.css">

<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/demo.css">

<!-- FAVICONS -->
<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">
<link rel="icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">

<!-- GOOGLE FONT -->
<link rel="stylesheet"
	href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">
		
<style type="text/css">
.btnThumb {
	position: relative;
	overflow: hidden;
}

.btnThumb input {
	position: absolute;
	top: 0;
	right: 0;
	margin: 0;
	border: solid transparent;
	opacity: 0;
	filter: alpha(opacity = 0);
	cursor: pointer;
}
#progress { position:relative; width:100%; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }  
#bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }  
#percent { position:absolute; display:inline-block; top:3px; left:48%; }  
</style>

<link rel="stylesheet" href="https://cache.amap.com/lbs/static/main1119.css"/>
<script src="http://cache.amap.com/lbs/static/es5.min.js"></script>
<script src="http://webapi.amap.com/maps?v=1.4.0&amp;key=0990c546f2f65aad75220acb10e2d4b9&plugin=AMap.Scale,AMap.OverView,AMap.ToolBar,aMap.Driving,AMap.Geocoder"></script>
<script type="text/javascript" src="http://cache.amap.com/lbs/static/addToolbar.js"></script>

</head>
<body class="" style="height: 2600px;">

	<!-- MAIN PANEL -->
	<div id="main" role="main">

		<!-- RIBBON -->
		<div id="ribbon">

			<span class="ribbon-button-alignment"> <span id="refresh"
				class="btn btn-ribbon" data-title="refresh" rel="tooltip"
				data-placement="bottom" data-original-title="<i
			
				
				class='text-warning fa fa-warning'></i> Warning! This will reset all
					your widget settings." data-html="true"><i class="fa fa-refresh"></i></span>
			</span>

			<!-- breadcrumb -->
			<ol class="breadcrumb">
				<li>铺源管理</li>
                <li>魔方铺源</li>
			</ol>
		</div>
		<!-- END RIBBON -->

		<!-- MAIN CONTENT -->
		<div id="content">

			<div class="row">
				<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
					<h1 class="page-title txt-color-blueDark">
						<i class="fa fa-edit fa-fw"></i> 魔方铺源 <span>> 修改店铺</span>
					</h1>
				</div>
				<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8"
					style="display: block;">

					<div class="col-sm-14 text-align-right"
						style="width: 100%; margin-top: 15px;">

						<div class="btn-group">
							<a href="index.php?m=admin&c=store&a=store"
								class="btn btn-sm bg-color-red txt-color-white"
								style="padding-left: 15px;"><i class="glyphicon glyphicon-list">
							</i> 店铺列表</a>
						</div>

						<div class="btn-group">
							<a href="javascript:void(0);" class="btn btn-sm btn-success"> <i class="fa fa-edit"></i> 修改店铺
							</a>
						</div>

					</div>

				</div>
			</div>
			<!-- widget grid -->
			<section id="widget-grid" class="">

				<div class="row" style="height: 1600px;">

					<!-- NEW WIDGET START -->
					<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

						<!-- Widget ID (each widget will need unique ID)-->
						<div class="jarviswidget jarviswidget-color-darken"
							id="wid-id-emp-add-edit_store" data-widget-colorbutton="false"
							data-widget-editbutton="false" style="height: 1300px;">
							<header>
								<span class="widget-icon"> <i class="fa fa-edit"></i></span>
								<h2 style="line-height: 30px;">修改店铺</h2>

							</header>

							<!-- widget div-->
							<div>

								<!-- widget edit box -->
								<div class="jarviswidget-editbox">
									<!-- This area used as dropdown edit box -->

								</div>
								<!-- end widget edit box -->
								<form id="form1" method="post" class="smart-form" action="index.php?m=admin&c=store&a=doUpdateStore">
									<input type="hidden" name="store_id" value="<{$store->id}>" />
									<!-- widget content -->
									<div
										class="col-sm-12 col-md-12 col-lg-6 sortable-grid ui-sortable">

										<!-- form -->


										<fieldset>
											<legend>位置信息</legend>

											<section style="clear: both;">
                                                <label class="label">定位位置 </label>
												<label class="select">
													<select name="street" id="street" class="valid" style="">
														<option value="" >请选择街道</option>
														<option value="<{$store->street}>" selected ><{$store->district}> - <{$store->street}></option>
												</select> <i></i>
												</label>
											</section>
											
											<input type="hidden" name="province" id="province" value="<{$store->province}>" />
											<input type="hidden" name="city" id="city" value="<{$store->city}>" />
											<input type="hidden" name="district" id="district" value="<{$store->district}>" />
											
											<input type="hidden" name="location_lat" id="location_lat" value="<{$store->location_lat}>" />
											<input type="hidden" name="location_lng" id="location_lng" value="<{$store->location_lng}>" />
											

											<section>
												<label class="input">街铺编号 <input type="text" value="<{$store->street_sn}>" id="street_sn" name="street_sn" placeholder="街铺编号"> <i></i>
												</label>
											</section>

											<section>
												<label class="label">地址备注</label> <label
													class="textarea"> <textarea rows="3"
														class="custom-scroll" name="memo_address"
														id="memo_address" placeholder="地址备注"><{$store->memo_address}></textarea>
													<i></i>
												</label>
											</section>

										</fieldset>

										 
									</div>
                                    
                                    <div
										class="col-sm-12 col-md-12 col-lg-4 sortable-grid ui-sortable" id="mapInfo" style="width: 50%;height: 400px;">

                                                       
                                    </div>
                                    
                                    
                                    <div
										class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

										 


										<fieldset>
											<legend>基本信息</legend>

											<section class="col-lg-6">
												<label class="input">当前店名 <input type="text" 
													name="present_operation" id="present_operation" value="<{$store->present_operation}>"
													placeholder="当前店名"> <i></i>
												</label>
											</section>									
											
											<section class="col-lg-4" style="margin-left: 20px;">
                                                <label class="label" style="margin-bottom: 0;line-height: 18px;">当前行业 </label>
												<label class="select"><select name="trade" id="trade" 
													class="valid">
														<option value="" selected >请选择</option>
														<{foreach $trade_attrs as $pro}>
														<option value="<{$pro}>" <{if $pro eq $store->trade}> selected <{/if}> ><{$pro}></option>
														<{/foreach}> 
															 
												</select> <i></i>
												</label>
											</section>
                                            
                                            <section class="col-lg-6" style="clear: both;">
                                                <label class="label">物业性质 </label>
												<label class="select"><select name="property" id="property" 
													class="valid" style="">
														<option value="" selected >请选择</option>
														<{foreach $property_attrs as $pro}>
														<option value="<{$pro}>" <{if $pro eq $store->property }> selected <{/if}> ><{$pro}></option>
														<{/foreach}> 
															 
												</select> <i></i>
												</label>
											</section>
                                            
                                            <section class="col-lg-5" style="margin-left: 20px;">
												<label class="label">基础配套</label>
												<div class="inline-group">
													<{foreach $basicInfo as $basic}> <label class="checkbox"> <input
														type="checkbox" name="basic_installation_ids[]"
														value="<{$basic->id}>"<{if
														in_array($basic->id,$checkedBasic) }> checked="checked"
														<{/if}> > <i></i><{$basic->name}>
													</label> <{/foreach}>
												</div>
											</section>
                                            
                                            <section class="col-lg-2" style="clear: both">
												<label class="label">额外配套</label>
												<div class="inline-group">
													<{foreach $extraInfo as $extra}> <label class="checkbox"> <input
														type="checkbox" name="extra_installation_ids[]"
														value="<{$extra->id}>"<{if
														in_array($extra->id,$checkedExtra) }> checked="checked"
														<{/if}>> <i></i><{$extra->name}>
															</label>
													<{/foreach}>
												</div>
											</section>
                                            
                                            <section class="col-lg-4">
												<label class="input">门头宽度（米） <input type="text" id="door_width"
													name="door_width" placeholder="门头宽度"
													value="<{$store->door_width}>"> <i></i>
												</label>
											</section>

											<section class="col-lg-1" style="margin-left:20px;">
												<label class="input">共</label> <input type="text" id="floor_total"
													name="floor_total" placeholder="共几层"
													value="<{$store->floor_total}>" style="width:60px;float:left;"><span style="float:left;">层</span>
                                            </section>
                                            <section class="col-lg-1" style="margin-left:5px;">
                                                <label class="input">第</label> <input type="text" id="floor_start"
													name="floor_start" placeholder="第几层"
													value="<{$store->floor_start}>" style="width:60px;float:left;"><span style="float:left;">层</span>
                                            </section>
                                            <section class="col-lg-1" style="margin-left:5px;">
                                                <label class="input">到</label> <input type="text" id="floor_end"
													name="floor_end" placeholder="到几层"
													value="<{$store->floor_end}>" style="width:60px;float:left;"><span style="float:left;">层</span>
											</section>
											
											
											<section class="col-lg-2" style="clear: both">
												<label class="input">建筑面积（单位：㎡） <input type="text" 
													name="build_area" id="build_area" value="<{$store->build_area}>"
													placeholder="建筑面积"> <i></i>
												</label>
											</section>

											<section class="col-lg-3" style="margin-left: 20px;">
												<label class="input">使用面积（单位：㎡） <input type="text" 
													value="<{$store->use_area}>" id="use_area"
													name="use_area" placeholder="使用面积"> <i></i>
												</label>
											</section>
										
											<section class="col-lg-5" style="margin-left: 130px;">
												<label class="label">标签</label>
												<div class="inline-group">
													<{foreach $tagsInfo as $tag}> <label class="checkbox"> <input
														type="checkbox" name="tag_ids[]"
														value="<{$tag}>"<{if
														in_array($tag,$storeTags) }> checked="checked"
														<{/if}> > <i></i><{$tag}>
													</label> <{/foreach}>
												</div>
											</section>
											
											
											<section style="clear: both;">
												<label class="label">条件备注</label> <label
													class="textarea"> <textarea rows="5"
														class="custom-scroll" name="conditional_remark"
														id="conditional_remark" placeholder="条件备注"><{$store->conditional_remark}></textarea>
													<i></i>
												</label>
											</section>
											

										</fieldset>



										<fieldset id="swap_contacts">
											<legend>
												联系信息 <a href="javascript:void(0);" id="btnAddContacts"
													class="btn btn-info btn-xs" style="float: right;"> <i
													class="fa fa-plus"></i> 新增
												</a>
											</legend>
											<{foreach $contacts as $contact}>
											<div class="col-lg-12" id="contact_swap_<{$contact->id}>"
												data="<{$contact->id}>">
												<input type="hidden" name="number[]"
													value="<{$contact->id}>" />
												<section class="col-lg-6">
													<label class="input">姓名 <input type="text"
														name="contacts[]" value="<{$contact->contacts}>"
														placeholder="姓名"> <i></i>
													</label>
												</section>

												<section class="col-lg-4">
													<div class="inline-group"
														style="margin-top: 21px; margin-left: 30px;">
														<label class="radio"> <input type="radio"
															name="role_name_<{$contact->id}>[]" value="中介"<{if trim($contact->role_name) eq '中介' }> checked="checked" <{/if}> > <i></i>中介
														</label>
														<label class="radio"> <input type="radio"
															name="role_name_<{$contact->id}>[]" value="房东"<{if trim($contact->role_name) eq '房东' }> checked="checked" <{/if}> > <i></i>房东
														</label>
														<label class="radio"> <input type="radio"
															name="role_name_<{$contact->id}>[]" value="经营者"<{if trim($contact->role_name) eq '经营者' }> checked="checked" <{/if}> > <i></i>经营者
														</label>

													</div>
												</section>

												<section class="col-lg-4" style="clear: both;">
													<label class="input">电话 <input type="text"
														value="<{$contact->phone}>" name="phone[]"
														placeholder="电话"> <i></i>
													</label>
												</section>

												<section class="col-lg-4">
													<label class="input">微信 <input type="text"
														value="<{$contact->wechat}>" name="wechat[]"
														placeholder="如有特殊情况请写明"> <i></i>
													</label>
												</section>
												<section class="col-lg-4">
													<a href="javascript:void(0);"
														class="btn btn-xs btn-success"
														style="margin-top: 24px; margin-left: 10px;" onclick="setWechatPhone(<{$contact->id}>);">同电话</a> <a
														onclick="deleteContact(<{$contact->id}>)"
														class="btn btn-danger btn-xs"
														style="margin-top: 24px; float: right;"
														href="javascript:void(0);">删除</a>
												</section>
											</div>
											<{/foreach}>



										</fieldset>
										
										
										
										<fieldset>
											<legend>费用信息</legend>

											<section class="col-lg-1">
												<label class="input">租金 <input type="text"
													name="rental_value" id="rental_value"
													value="<{$rental_value}>" placeholder="租金"> <i></i>
												</label>
											</section>

											<section class="col-lg-1">
												<label class="select"><select name="rental_type" id="rental_type" 
													class="valid" style="margin-top: 18px; margin-left: 10px;">
														<option value=""<{if $store->rental_type eq '' }> selected
															<{/if}> >选中租金单位</option>
														<option value="1"<{if $store->rental_type eq '1' }>
															selected <{/if}>>元/平/天</option>
														<option value="2"<{if $store->rental_type eq '2' }>
															selected <{/if}>>万/月</option>
														<option value="3"<{if $store->rental_type eq '3' }>
															selected <{/if}>>万/年</option>
												</select> <i></i>
												</label>
											</section>
											
											<section class="col-lg-1" style="margin-left:20px;">
												<label class="input">转让费(单位：万) <input type="text"
													id="transfer_fee" name="transfer_fee" placeholder="转让费"
													value="<{$store->transfer_fee}>"> <i></i>
												</label>
											</section>
											
											<section class="col-lg-1" style="margin-left: 20px;">
                                                <label class="label" style="margin-bottom: 0;line-height: 18px;">押 </label>
												<label class="select" style="margin-top:0;">
													<select name="payment_deposit" id="payment_deposit" 
													class="valid" style="">
														<option value="" selected >请选择押几个月</option>
														<{foreach $payments_attrs as $dep}>
															<option value="<{$dep}>" <{if $store->payment_deposit eq $dep}> selected <{/if}> ><{$dep}></option>
														<{/foreach}>	
															 
												</select> <i></i>
												</label>
											</section>
											
											<section class="col-lg-1" style="margin-left: 10px;">
                                                <label class="label" style="margin-bottom: 0;line-height: 18px;">付 </label>
												<label class="select">
													<select name="payment_pay" id="payment_pay" 
													class="valid" style="">
														<option value="" selected >请选择付几个月</option>
														<{foreach $payments_attrs as $dep}>
															<option value="<{$dep}>" <{if $store->payment_pay eq $dep}> selected <{/if}> ><{$dep}></option>
														<{/foreach}>		 
												</select> <i></i>
												</label>
											</section>
											
											<section class="col-lg-2" style="margin-left:20px;">
												<label class="input">剩余租约（单位：月） <input type="text"
													id="residual_lease" name="residual_lease" placeholder="剩余租约"
													value="<{$store->residual_lease}>"> <i></i>
												</label>
											</section>
											
											<section class="col-lg-2" style="margin-left:20px;">
												<label class="input">最短租期（单位：年） <input type="text"
													id="min_lease" name="min_lease" placeholder="最短租期"
													value="<{$store->min_lease}>"> <i></i>
												</label>
											</section>
											
											<section style="clear: both;">
												<label class="label">费用备注</label> <label
													class="textarea"> <textarea rows="5"
														class="custom-scroll" name="charge_remark"
														id="charge_remark" placeholder="费用备注"><{$store->charge_remark}></textarea>
													<i></i>
												</label>
											</section>	
											
										</fieldset>

										
										<fieldset>
											<legend>维护信息</legend>

											<section class="col-lg-12">
												店铺状态
												<div class="inline-group"
													style="margin-top: 21px; margin-left: 30px;">
													<label class="radio"> <input type="radio" name="status"
														value="0"<{if $store->status eq 0}> checked <{/if}>> <i></i>转租中
													</label> <label class="radio"> <input type="radio"
														name="status" value="1"<{if $store->status eq 1}> checked
														<{/if}>> <i></i>营业中
													</label>
													
												</div>
											</section>
											
											<section class="col-lg-12">
												店铺性质
												<div class="inline-group"
													style="margin-top: 21px; margin-left: 30px;">
													<label class="radio"> <input type="radio" name="source"
														value="正常扫铺"<{if $store->source eq "正常扫铺"}> checked <{/if}> > <i></i>正常扫铺
													</label> <label class="radio"> <input type="radio"
														name="source" value="挖铺"<{if $store->source eq "挖铺"}>
														checked <{/if}>> <i></i>挖铺
													</label>
												</div>
											</section>
											
											<section class="col-lg-12">
												<label class="input">维护时间（单位：天） <input type="text" value="<{$store->oam_times}>" id="oam_times" name="oam_times" placeholder="维护时间"> <i></i>
												</label>
											</section>										
											
										</fieldset>
										
										<fieldset>
											<legend>
												店铺图片
												<div class="btnThumb btn btn-info btn-xs"
													style="float: right;">
													<span><i class="fa fa-plus"></i> 新增</span> <input
														id="fileupload" type="file" name="mypic">
												</div>

											</legend>
											<div class="dropzone dz-clickable dz-started" id="swap_thumb">
												<input type="hidden" name="store_thumbs" id="store_thumbs" value="" />
												
												 <div id="progress" style="display: none;width: 100%;">  
															<div id="bar"></div>  
															<div id="percent">0%</div >  
										          </div>
												
												<{foreach $thumbs as $thumb}>
												<div
													class="dz-preview dz-processing dz-success dz-image-preview"
													id="qiniu_<{$thumb['qiniu_key']}>" data="<{$thumb['qiniu_key']}>">
													<div class="dz-details">
														<div class="dz-filename">
															<span data-dz-name=""></span>
														</div>
														<div class="dz-size" data-dz-size="">
															<strong></strong>
														</div>
														<a href="<{$thumb['original_url']}>" target="_blank" /> <img
															data-dz-thumbnail="" alt="" src="<{$thumb['thumb_url']}>">
														</a>
													</div>
													<div class="dz-progress">
														<span class="dz-upload" data-dz-uploadprogress=""
															style="width: 100%;"></span>
													</div>
													<div class="dz-error-mark">
														<span><i class="fa fa-times"></i></span>
													</div>
													<div class="dz-error-message">
														<span data-dz-errormessage=""></span>
													</div>
													<a class="btn btn-sm btn-danger btn-block"
														href="javascript:void(0);"
														onclick="deleteThumb('<{$thumb['qiniu_key']}>');">删除</a>
												</div>
												<{/foreach}>

											</div>


										</fieldset>

										 
									</div>

										</fieldset>




									</div>

									<div class="col-sm-12 col-md-12 sortable-grid ui-sortable">
										<footer style="margin-bottom: 30px;">
											
											<button type="button" class="btn btn-default"
												onclick="window.history.back();">返 回</button>
											
											<button id="btnSubmit" type="button" class="btn btn-primary">
												提交修改</button>
											 
										</footer>
									</div>
									 

									<!-- end widget content -->
								</form>
							</div>
							<!-- end widget div -->

						</div>
						<!-- end widget -->

					</article>
					<!-- WIDGET END -->


				</div>


			</section>
			<!-- end widget grid -->

		</div>
		<!-- END MAIN CONTENT -->
		<div class="col-sm-12 col-md-12 sortable-grid ui-sortable"
			style="height: 20px; width: 100%; margin-top: 50px; clear: both;">&nbsp;</div>
	</div>
	 

</body>
</html>
<script data-pace-options='{ "restartOnRequestAfter": true }'
	src="/resources/js/plugin/pace/pace.min.js"></script>
<script>
    if (!window.jQuery) {
        document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
    }
</script>

<script>
    if (!window.jQuery.ui) {
        document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
    }
</script>

<script src="/resources/js/jquery.alerts.js" type="text/javascript"></script>
<link href="/resources/css/jquery.alerts.css" rel="stylesheet"
	type="text/css" media="screen" />
<script src="/resources/jquery.form.js"></script>
<script src="/resources/js/jquery.validate.js"></script>
<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
<script src="/resources/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

<!-- BOOTSTRAP JS -->
<script src="/resources/js/bootstrap/bootstrap.min.js"></script>

<!-- CUSTOM NOTIFICATION -->
<script src="/resources/js/notification/SmartNotification.min.js"></script>

<!-- JARVIS WIDGETS -->
<script src="/resources/js/smartwidgets/jarvis.widget.min.js"></script>

<!-- EASY PIE CHARTS -->
<script
	src="/resources/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

<!-- SPARKLINES -->
<script src="/resources/js/plugin/sparkline/jquery.sparkline.min.js"></script>

<!-- JQUERY VALIDATE -->
<script
	src="/resources/js/plugin/jquery-validate/jquery.validate.min.js"></script>

<!-- JQUERY MASKED INPUT -->
<script
	src="/resources/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

<!-- JQUERY SELECT2 INPUT -->
<script src="/resources/js/plugin/select2/select2.min.js"></script>



<!-- browser msie issue fix -->
<script src="/resources/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

<!-- FastClick: For mobile devices -->
<script src="/resources/js/plugin/fastclick/fastclick.js"></script>

<!--[if IE 7]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->

<!-- Demo purpose only -->
<script src="/resources/js/demo.js"></script>

<!-- MAIN APP JS FILE -->
<script src="/resources/js/app.js"></script>

<script
	src="/resources/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
<script src="/resources/js/plugin/datatables/ColReorder.min.js"></script>
<script src="/resources/js/plugin/datatables/FixedColumns.min.js"></script>
<script src="/resources/js/plugin/datatables/ColVis.min.js"></script>
<script src="/resources/js/plugin/datatables/ZeroClipboard.js"></script>
<script src="/resources/js/plugin/datatables/media/js/TableTools.min.js"></script>
<script src="/resources/js/plugin/datatables/DT_bootstrap.js"></script>
<script src="/resources/layer/layer.js"></script>
<script type="text/javascript">

	var map = new AMap.Map('mapInfo', {
        resizeEnable: true,
        zoom: 15,
        center: [<{$store->location_lng}>,<{$store->location_lat}>],
        mapStyle: 'amap://styles/fresh'
    });
	
	
	function Move(map, coordinate, title) {
        var marker = new AMap.Marker({
            position: coordinate || null,//marker所在的位置
            //icon: 'http://ozc9gamh2.bkt.clouddn.com/web1511311658864?imageView2/1/w/100/h/100',//自定义的图片
            title: title,
            animation: 'AMAP_ANIMATION_DROP',//marker的动画效果
            draggable: true,//是否可可移动
            raiseOnDrag: true,//拖拽点离开地图的效果
            map: map//创建时直接赋予map属性
        });
        /*var _onClick = function (e) {
            console.log(e)
            console.log(e.target.F.title)
        }
        AMap.event.addListener(marker, 'click', _onClick)*/

        //鼠标点击marker弹出自定义的信息窗体
        AMap.event.addListener(marker, 'mouseout', function(e) {
            
			 console.log(e.lnglat.lat);
			 console.log(e.lnglat.lng);
			 
			 $("#location_lat").val( e.lnglat.lat );
			 $("#location_lng").val( e.lnglat.lng );
			 var lnglatXY = [e.lnglat.lng, e.lnglat.lat]; //已知点坐标
			 regeocoder(lnglatXY);
			
        });
		
    }
		
    function regeocoder(lnglatXY) {  //逆地理编码
        var geocoder = new AMap.Geocoder({
            radius: 1000,
            extensions: "all"
        });        
        geocoder.getAddress(lnglatXY, function(status, result) {
            if (status === 'complete' && result.info === 'OK') {
                geocoder_CallBack(result);
            }
        });        
        //var marker = new AMap.Marker({  //加点
        //    map: map,
        //    position: lnglatXY
        //});
        ///map.setFitView();
    }
    function geocoder_CallBack(data) {
        var address = data.regeocode.formattedAddress; //返回地址描述
        //document.getElementById("result").innerHTML = address;
		var province = data.regeocode.addressComponent.province;
		var city = data.regeocode.addressComponent.city;
		var district = data.regeocode.addressComponent.district;
		
		$("#province").val( province );
		$("#city").val( city );
		$("#district").val( district );
		//console.log( data.regeocode.addressComponent );
		 
		///console.log( data.regeocode );
		
		$("#street").empty();
		
		for(i=0;i< data.regeocode.roads.length;i++ ){
			
			//console.log( data.regeocode.roads[i].name );
			$("#street").append("<option value='"+data.regeocode.roads[i].name+"'>"+district+" - "+data.regeocode.roads[i].name+"</option>");  
		}
		//nbox( "请选择定位位置",1 );		
    }
	
    Move(map, [<{$store->location_lng}>,<{$store->location_lat}>], "<{$store->district}> - <{$store->street}><{$store->street_sn}>号");


function isNull(str) {
    if (str == "") return true;
    var regu = "^[ ]+$";
    var re = new RegExp(regu);
    return re.test(str);
}

function deleteThumb(key){
	$("#qiniu_"+key).remove();
	$("#myupload").remove();
	nbox("删除成功",1);
}


function updateTagInput(){
   var tags = "";
   $("#swap_tag div").each(function(){
		tags+=$(this).attr('id')+',';
   });
   var reg=/,$/gi;
   tags=tags.replace(reg,""); 	
   $("#tag_ids").val(tags);
}

function deleteTag(id){
	nbox("标签删除成功",1);
	$("#swap_tag").find("#"+id).remove();
	updateTagInput();
	
}

function setWechatPhone(number){
	 //$("input[id='input_text2']").val();  
	var phone = $("#contact_swap_"+number).find("input[name='phone[]']").val();
	if(isNull(phone)){
		nbox("手机号码不能为空！",0);
		return false;
	}
	var mobile =  /^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1})|(14[0-9]{1})|(17[0-9]{1}))+\d{8})$/;
	var tel = /^\d{3,4}-?\d{7,9}$/;

	if( /-/.test(phone) ){
		  if( !tel.test(phone)){
		    canSubmit = false;
			nbox("电话号码格式错误",0);
			return false;
		  }
	 }else if(phone.length!=11 || !mobile.test(phone) ){
	         
	        canSubmit = false;
			nbox("手机号码格式错误",0);
			return false;
	 }
	$("#contact_swap_"+number).find("input[name='wechat[]']").val( phone );
}

function deleteContact(number){
	nbox("删除成功",1);
	$("#contact_swap_"+number).remove();
}

function closeLayer(){
	 layer.closeAll();
	 
}

  $(function(){

        pageSetUp();

		//删除标签
		$("#swap_tag span").click(function(){

			$(this).parent().remove();
			updateTagInput();
			
		});
		
		
		$("#btnModifyTag").click(function(){
			
				updateTagInput();
				var tag_ids = $("#tag_ids").val();
			 
			    var index = layer.open({
			      type: 2,
			      title: '修改标签',
			      maxmin: false,
			      shadeClose: true, //点击遮罩关闭层
			      area : ['600px' , '320px'],
			      content: "index.php?m=admin&c=store&a=addStoreTag"
			    });
			 
		});
		
		 
        $("#btnAddContacts").click(function(){
			var number = 0
			$("#swap_contacts .col-lg-12").each(function(){
				var div_number = $(this).attr('data');
				if(parseInt(div_number)>number){
					number = parseInt(div_number);
				}
			});			 
			
        	$.ajax({  
          	      type:"POST",  
          	      async:false,  
          	      url:"index.php?m=admin&c=store&a=getContactTmp",  
          	      data:{number:parseInt(number)+1},  
          	      success:function(data){  

					$("#swap_contacts").append( data );
            	         
          	     }
      	    });
	
			
		});



		//上传图
        $("#fileupload").wrap("<form id='myupload' action='index.php?m=admin&c=store&a=uploadPic' method='post' enctype='multipart/form-data'></form>");
        $("#fileupload").change(function(){
    		$("#myupload").ajaxSubmit({
    			dataType:  'json',
    			beforeSend: function() {
					$("#progress").show();  
					//clear everything  
					$("#bar").width('0%');  
					//$("#message").html("");  
					$("#percent").html("0%");  
        		},
        		uploadProgress: function(event, position, total, percentComplete) {
					
					$("#bar").width(percentComplete+'%');  
				    $("#percent").html(percentComplete+'%');  
					
        		},
    			success: function(data) {
//     				console.log( data );
					nbox("图片上传成功",1);
    				$("#swap_thumb").append(data.str);
					$("#progress").hide();  
    			},
    			error:function(xhr){
    				//alert("上传失败");
    				nbox( xhr.responseText,0 );
    			},
				complete: function(response)   
				{  
					 
				} 
    		});
    	});
		
		$("#btnSubmit").click(function(){
			updateTagInput();		
			
			var store_thumbs = '';
			$("#swap_thumb .dz-preview").each(function(){
				store_thumbs += $(this).attr('data')+",";
			});
			$("#store_thumbs").val( store_thumbs );

			$("#form1").ajaxSubmit({
				dataType: "json", 
				success : function(data) {
					if (data.status == 1) {
						 nbox(data.msg,1);
						 setTimeout(function(){
								window.location.href="index.php?m=admin&c=store&a=store";		
							},2000);			
					}
					else{
						 nbox(data.msg,0);
					}
				}
			});
			

		});
		

    });
</script>