<!DOCTYPE html>
<html lang="en-us">
<head>
<meta charset="utf-8">
<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

<title>铺军师(管理工具)</title>
<meta name="description" content="">
<meta name="author" content="">
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    
<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->

<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Basic Styles -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/font-awesome.min.css">

<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-production.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-skins.css">

<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/demo.css">

<!-- FAVICONS -->
<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">
<link rel="icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">

<!-- GOOGLE FONT -->
<link rel="stylesheet"
	href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">
		
<style type="text/css">
.btnThumb {
	position: relative;
	overflow: hidden;
}

.btnThumb input {
	position: absolute;
	top: 0;
	right: 0;
	margin: 0;
	border: solid transparent;
	opacity: 0;
	filter: alpha(opacity = 0);
	cursor: pointer;
}
#progress { position:relative; width:100%; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }  
#bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }  
#percent { position:absolute; display:inline-block; top:3px; left:48%; }
.error{ border:1px solid red;margin-top:5px;}
label.error{ border:1px solid red;margin-top:5px;background: red;color:#fff;  }
</style>
</head>
<body class="" style="height: 1100px;">
<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- RIBBON -->
	<div id="ribbon">

		<span class="ribbon-button-alignment"> <span id="refresh"
			class="btn btn-ribbon" data-title="refresh" rel="tooltip"
			data-placement="bottom" data-original-title="<i 
			class='text-warning fa fa-warning'></i> Warning! This will reset all
				your widget settings." data-html="true"><i class="fa fa-refresh"></i></span>
		</span>

		<!-- breadcrumb -->
		<ol class="breadcrumb">
			<li>运营管理</li>
            <li>版本升级</li>
		</ol>
	</div>
	<!-- END RIBBON -->

	<!-- MAIN CONTENT -->
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					<i class="fa fa-list-alt"></i> 版本升级 <span>> 编辑版本</span>
				</h1>
			</div>
			<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8"
				style="display: block;">
				 <div class="col-sm-14 text-align-right" style="width: 100%;margin-top:15px;">
                    
                     <div class="btn-group">
                        <a
                            href="index.php?m=admin&c=operation&a=createUpgrade"
                            class="btn btn-sm btn-success"> <i class="fa fa-plus"></i>
                            添加版本
                        </a>
                    </div>      

                    <div class="btn-group">
                        <a href="index.php?m=admin&c=operation&a=upgrade" class="btn btn-sm bg-color-red txt-color-white"
                           style="padding-left: 15px;"><i
                                class="glyphicon glyphicon-list"> </i> 数据列表</a>
                    </div>
                         
				 </div>				
			</div>
		</div>
		<!-- widget grid -->
		<section id="widget-grid" class="">

			<div class="row">

				<!-- NEW WIDGET START -->
				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-upgrade-edit"
						data-widget-editbutton="true" data-widget-sortable="true" data-widget-fullscreenbutton="false">
						<header>
							<span class="widget-icon"> <i class="fa fa-edit"></i></span>
							<h2 style="line-height: 30px;">编辑版本</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							 <div class="widget-body">
				
										<form id="form1" class="form-horizontal">
											<input type="hidden" name="editId" value="<{$row->id}>" />
											<fieldset>
												 
												<div class="form-group" style="margin-top:30px;">
													<label class="col-md-1 control-label" style="float:left;">版本号</label>
													<div class="col-md-10" style="float:left;">
														<input class="form-control" placeholder="版本号" type="text" name="version_sn" id="version_sn" value="<{$row->version_sn}>">  <i></i>
													</div>
												</div>
												
												<div class="form-group">
													<label class="col-md-1 control-label">更新话术</label>
													<div class="col-md-10">
														<textarea class="form-control" placeholder="更新话术" rows="4" name="message" id="message"><{$row->message}></textarea>  <i></i>
													</div>
												</div>
                                                
                                                <div class="form-group">
													<label class="col-md-1 control-label">备注</label>
													<div class="col-md-10">
														<textarea class="form-control" placeholder="备注" rows="4" name="remark" id="remark"><{$row->remark}></textarea>  <i></i>
													</div>
												</div>
											
												<div class="form-group">
													<label class="col-md-1 control-label">更新系统</label>
													<div class="col-md-10">
														<label class="checkbox-inline">
															  <input type="checkbox" class="checkbox style-0" name="up_system[]" value="1" <{if in_array(1,$up_system_arr)}> checked <{/if}>>
															  <span>IOS </span>
														</label>
														<label class="checkbox-inline">
															  <input type="checkbox" class="checkbox style-0" name="up_system[]" value="2" <{if in_array(2,$up_system_arr)}> checked <{/if}>>
															  <span>Android</span>
														</label>
                                                        
													</div><div id="tip_up_system" style="clear: both;margin-left: 148px;"></div>
												</div>
												 
												<div class="form-group">
													<label class="col-md-1 control-label">更新方式</label>
													<div class="col-md-10">
														<label class="radio radio-inline">
															<input type="radio" name="up_method" value="1" <{if $row->up_method eq 1}>checked<{/if}>>
															强制升级 </label>
														<label class="radio radio-inline">
															<input type="radio" name="up_method" value="2" <{if $row->up_method eq 2}>checked<{/if}>>
															提示升级 </label>
                                                        <i></i>
													</div>
                                                    
												</div>
											 
											</fieldset>
											
											<div class="form-actions">
												<div class="row">
													<div class="col-md-6">
														<button id="btnSubmit" type="button" class="btn btn-primary">
                                                            提 交</button>
                                                        <button type="button" class="btn btn-default"
                                                            onclick="window.history.back();">返 回</button>
													</div>
												</div>
											</div>
				
										</form>
				
									</div>

                        </div>
					<!-- end widget -->

				</article>
				<!-- WIDGET END -->


			</div>


		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->

</div>

</body>
</html>
<script>
    if (!window.jQuery) {
        document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
    }
</script>

<script>
    if (!window.jQuery.ui) {
        document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
    }
</script>

<script src="/resources/js/jquery.alerts.js" type="text/javascript"></script>
<link href="/resources/css/jquery.alerts.css" rel="stylesheet"
	type="text/css" media="screen" />
<script src="/resources/jquery.form.js"></script>
<script src="/resources/js/jquery.validate.js"></script>
<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
<script src="/resources/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

<!-- BOOTSTRAP JS -->
<script src="/resources/js/bootstrap/bootstrap.min.js"></script>

<!-- CUSTOM NOTIFICATION -->
<script src="/resources/js/notification/SmartNotification.min.js"></script>

<!-- JARVIS WIDGETS -->
<script src="/resources/js/smartwidgets/jarvis.widget.min.js"></script>

<!-- EASY PIE CHARTS -->

<!-- SPARKLINES -->
<script src="/resources/js/plugin/sparkline/jquery.sparkline.min.js"></script>

<!-- JQUERY MASKED INPUT -->
<script
	src="/resources/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

<!-- JQUERY SELECT2 INPUT -->
<script src="/resources/js/plugin/select2/select2.min.js"></script>



<!-- browser msie issue fix -->
<script src="/resources/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

<!-- FastClick: For mobile devices -->
<script src="/resources/js/plugin/fastclick/fastclick.js"></script>

<!--[if IE 7]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->

<!-- MAIN APP JS FILE -->
<script src="/resources/js/app.js"></script>
<script src="/resources/js/demo.js"></script>
<script src="/resources/layer/layer.js"></script>
<script type="text/javascript">
$(function(){
	pageSetUp();
    
    $.datepicker.regional["zh-CN"] = { closeText: "关闭",currentText: "今天", monthNames: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"], dayNames: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"], dayNamesShort: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"], dayNamesMin: ["日", "一", "二", "三", "四", "五", "六"], weekHeader: "周", dateFormat: "yy-mm-dd", firstDay: 1, isRTL: !1, showMonthAfterYear: !0, yearSuffix: "年" }
    $.datepicker.setDefaults($.datepicker.regional["zh-CN"]);
    
    $('.date').datepicker({
		showOtherMonths: true,
        selectOtherMonths: true,  
        changeMonth: true,
        changeYear: true,
        prevText : '<i class="fa fa-chevron-left"></i>',
		nextText : '<i class="fa fa-chevron-right"></i>',
		dateFormat : 'yy-mm-dd'
	});    
    
    validator = $("#form1").validate({
         rules: {
        	 version_sn:{
			     required:true
			 },
             message:{
                required:true
                },
             up_system: {
                required: true
              }
             
         },
         messages: {
        	 version_sn:{
			    required:"版本号不能为空！"
			 },
             message:{
                required:"更新术语不能为空！"
             },
             up_system:{
                required:"请选择更新系统方式"
             } 
               
         },
        errorPlacement: function(error, element) {  
             //error.appendTo(element.parent());
             //if (error.html() != "" && element.attr("name") == "up_system") {
             //   
             //    $('#tip_up_system').addClass("note").css({"color":'red'}).html( error.html() );
             //   
             //}else{
             //   
             //  
             //}
             
              error.appendTo(element.parent().parent());
            
            
        }

   });
	
	$("#btnSubmit").click(function(){
		fValidator.save();
	});

	var fValidator = {
			 save:function(){
				    if( validator.form() ){
                    
                    var index = layer.load(2, {
                            shade: [0.1,'#fff'] //0.1透明度的白色背景
                          });
                                                   
                    var form = $('#form1');
                    var ajax = {
                        url:"index.php?m=admin&c=operation&a=doEditUpgrade",
                        data: form.serialize(),
                        type: 'post',
                        dataType: 'json',
                        cache: false,
                        success: function(res, statusText) {
                            layer.closeAll();
                            if(res.status==0){
                                
                                nbox(res.msg,0);
                                return false;
                                
                            }else if(res.status==1){
                                nbox(res.msg,1);
                                setTimeout(function(){
                                    window.location.href="index.php?m=admin&c=operation&a=upgrade";
                                    },2000);
                            }                                     
                            
                        },
                        error: function(httpRequest, statusText, errorThrown) {
                            return false;
                        }
                    };
                    $.ajax(ajax);
				    return false;
			      }
			 }
	};
    
    

	
});

</script>


