<!DOCTYPE html>
<html lang="en-us">
<head>
<meta charset="utf-8">
<!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

<title>铺军师(管理工具)</title>
<meta name="description" content="">
<meta name="author" content="">

<!-- Use the correct meta names below for your web application
			 Ref: http://davidbcalhoun.com/2010/viewport-metatag 
			 
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">-->

<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Basic Styles -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/font-awesome.min.css">

<!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-production.css">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/smartadmin-skins.css">

<!-- SmartAdmin RTL Support is under construction
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/smartadmin-rtl.css"> -->

<!-- We recommend you use "your_style.css" to override SmartAdmin
		     specific styles this will also ensure you retrain your customization with each SmartAdmin update.
		<link rel="stylesheet" type="text/css" media="screen" href="/resources/css/your_style.css"> -->

<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/css/demo.css">

<!-- FAVICONS -->
<link rel="shortcut icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">
<link rel="icon" href="/resources/img/favicon/favicon.ico"
	type="image/x-icon">

<!-- GOOGLE FONT -->
<link rel="stylesheet"
	href="/resources/css/admin_css.css?family=Open+Sans:400italic,700italic,300,400,700">
<link rel="stylesheet" type="text/css" media="screen"
	href="/resources/js/libs/jquery-ui-timepicker-addon.css">
</head>
<body class="">
	<script>
    if (!window.jQuery) {
        document.write('<script src="/resources/js/libs/jquery-2.0.2.min.js"><\/script>');
    }
</script>

	<script>
    if (!window.jQuery.ui) {
        document.write('<script src="/resources/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
    }
</script>
    <script src="/resources/layer/layer.js"></script>

<div class="table-responsive">
											
											<table class="table table-bordered table-condensed">
												 
												<tbody>
													<tr class="well">
														<td>
                                                            
                                                            用户ID：<{$row->user_id}>
                                                        </td>
														<td>注册手机号：<{$phone}>
														</td>
														 
														<td>反馈时间：<{date('Y-m-d H:i',$row->created_at)}>
														</td>
													</tr>
													<tr class="well">
														<td colspan="4">反馈内容：<{$row->message}>              </td>
													</tr>
												</tbody>
											</table>
											
										</div>




</body>

<script>
function isNull(str) {
    if (str == "") return true;
    var regu = "^[ ]+$";
    var re = new RegExp(regu);
    return re.test(str);
}

$(function(){

	$("#btnClose").click(function(){
		parent.closeLayer(); 
	});
	
})


</script>